language: python

python:
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE chat WITH ENCODING 'utf8';" -U postgres

script:
  - python3 test_processors.py
  - python3 test_request_handler.py

notifications:
  email: false

  slack:
    rooms:
      - owllit:GRN6KTTcUiujsRDPbBROMEr0
    on_success: always
    on_failure: always
